add prototypes to fix -Werror=missing-prototypes
src/hexchat_otr.c:328:5: error: no previous prototype for ‘hexchat_plugin_deinit’ [-Werror=missing-prototypes]